name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk unzip git zlib1g-dev libncurses5 libstdc++6 \
            libffi-dev libssl-dev autoconf automake build-essential \
            libtool pkg-config python3-pip python3-setuptools \
            python3-wheel python3-dev

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer -v android debug
